# Stage 1: Build the app using Vite
FROM node:22.12.0-alpine  as build

WORKDIR /app

# Accept environment variables passed during build time
ARG VITE_API_URL
ARG VITE_SERVER_URL

# Use the build-time variables
ENV VITE_API_URL=${VITE_API_URL}
ENV VITE_SERVER_URL=${VITE_SERVER_URL}

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the source code into the container
COPY . .


# Expose the port your app is listening on (e.g., 5000 for backend)
EXPOSE 5173

# Run the app
CMD ["npm", "run", "dev"]





