# Use an official Node.js runtime as a parent image
FROM node:22.12.0-alpine 

# Set the working directory inside the container
WORKDIR /app

# Accept build-time environment variables
ARG MONGO_URI
ARG PORT
ARG JWT_SECRET
ARG NODE_ENV

# Set environment variables inside the container (available at runtime)
ENV MONGO_URI=${MONGO_URI}
ENV PORT=${PORT}
ENV JWT_SECRET=${JWT_SECRET}
ENV NODE_ENV=${NODE_ENV}

# Copy package.json and package-lock.json   for dependencies
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port your app is listening on (e.g., 5000 for backend)
EXPOSE 5000

# Run the app
CMD ["npm", "start"]
